# Generated by Django 6.1.1 on 2026-09-27 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='CSV файл')),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('SPLITTING', 'Разделение на чанки'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('total_rows', models.BigIntegerField(default=0, verbose_name='Всего строк')),
                ('processed_rows', models.BigIntegerField(default=0, verbose_name='Обработано строк')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Общая сумма транзакций')),
                ('category_summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка по категориям')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение обработки')),
            ],
            options={
                'verbose_name': 'Файл данных',
                'verbose_name_plural': 'Файлы данных',
                'ordering': ['-created_at'],
            },
        ),
    ]
